# Define a server for odoo backend (port 8069, as configured on the odoo.conf file (odoo file) )
upstream odoo-backend {
    server odoo:8069;
}

server {
    listen [::]:80;
    listen 80;
    server_name _;
    location ^~ /.well-known/acme-challenge {
        allow all;
        root /var/www/certbot;
    }
    location / {
        return  301 https://$host$request_uri;
    }
}